### ISSUE TITLE
Android app crashed on Pocophone F1

### ISSUE THREAD

**Issue by yarons** [jrandiny/pam-android-fingerprint#2]
`java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } in com.randiny_games.fingerprintauthenticator.server$1@a36a5b5 at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566) at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:224) at android.app.ActivityThread.main(ActivityThread.java:7520) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.net.wifi.WifiInfo.getIpAddress()' on a null object reference at com.randiny_games.fingerprintauthenticator.server$1.onReceive(server.java:82) at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556) ... 8 more`

Android 10.

**Comment by jrandiny** [comment]
Hmm I haven't tested the app with Android 10, looking at the error log it seems there's a change in some API. I will take a look at this in the coming months
